sudo: false
language: clojure
lein: 2.8.1
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

env:
 global:
  # Encrypted OC_TOKEN for deploying to OpenShift
  - secure: "DfOVuly9c/PotCGfy9VsarR9DZOSKrYs4faWZ0yQLMnFBcpua38srIlGUpdj0Fo2Omg459Z4Ok6lmBoVshbS+lcpkWZTbG38Mm7hlkbk+TsSd+nKuJgUhFFc67bKUdDf1uVpuAvosp6jcKtRctPHaJQr9TXMk5nVyeKeHBEx4TaMBbWN1zXz2Ie/hy0UgOvG5bEQGUS4JHQqIIWSzOeLrb87uyaPeWyDpW60nd1gNce/lBuQm7bOZkBfXBsILZTxG/Gcp/vZv6axqULenDHtDSuj/qGrOQDTXIdpnbGNr/zL6mBI6Y7oymw6WrbYT+j8JxRuVjJQ+KCvn8//Y5opgEtN1BrPR89Sm3O7QI8PyIXswNjbf4Z6V8ymdYBu9GXRr9TM7I7Rjq1VPcxJ+cbGFJVtoFKOS6Fp0AloQ8C1RYFlBu30GETn5vRdNVBCytUrXA2bKauL5vu3sZssGE9nfxisfySKnWaa7WI5x7nPRAxmjqdI7LZmFdTSE/0valw1yWA0klClFiB7BTPV9tqDdJYABCI1oLPrYBjV0tVgedYsJLbXYE2LgB6Lvxv6D7928JpMbPEGGfs0Bq7f6CR5ER7chtCaPPKVaNuENHNQFpKQK0Vk/ID466Lz0BlYYZArrGh9NvCVZKes619YqX3bI5/2/TXjaO+6i6zi1CejGHM="
  # Encrypted WHITESOURCE_TOKEN for updating Whitesource licensing information
  - secure: "Jft9IV9gern2M28DDTZ9sHBZS0nwWZ5GGYMM6dRQm2IRq8/wbpZuow9YHh0+8ZDSdp72g6SZlq7/B49ZepL979T+M/i9S4ialI9foCqd6ZHwgl/vPiSUS3wH8G2JoGCujk+iuCU2UxFL0Wc4hwqP+G6ZIB7XTyIfu4h/2WQWrTIFIWSHt4ZV7Yymegz3mO7HdUErRNUTcxCKYpLRJat0JMlBuSQjvMKAtUnjzd+nnrZ33T4DO0OOu/U26Sn7ofeDWjycGyXAo5/OR0TW98K3fK1jLsdaembwmjAhx9MQpOeHODQTEwjzR72PIWWqMxNapFWxpgPbIDFM1WaLEWymFyOgysiqc6OFDt8h0wPFgceapSP0dcBpeCvG8OmPP2S2W/5vpDV00HykHqzBje4XjEDT1hdrZVF63VItB8zJJKEO/CbizeDMfwJKWN1synIAIZKmtschhFEILbr0CBC9oOpU13c3oWb7wKmdHG2iRTfPxyzQb2J7BpW/7XS5P42Yte6dQWQtECZidwdRWUOTuT8qZAGJ4VFqvys1bxQnWM+NMwxPPX+q9JhXRngliDJleVtlENWd2UVXUBIogy4ousbf68Ll4L6delKb9xmItFn3ydnhuBzJaWOe7vpfJhN2L2uyoZXCmuFl4K5mzWAMO78AeHIUup/zY7YwDEjiD+I="

script: lein do git-info-edn, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"
      jdk: oraclejdk8
  # Update Whitesource
  - provider: script
    skip_cleanup: true
    script: lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.3.1:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN -Dorg.whitesource.ignoredScopes=test,runtime,provided,system
    on:
      branch: master
      jdk: oraclejdk8
