sudo: false
language: clojure
lein: 2.8.1
jdk:
  - oraclejdk8
  - oraclejdk9

env:
 global:
  # Encrypted OC_TOKEN for deploying to OpenShift
  - secure: "dxRPrX21vRYE726ot1GrQ4V4AdvWT7GfDRlFbGY1AQlSusQSM34f5tqNMN6dttYEA3KICojtyBruT1jy0ZprUdo5ZJxfM5UNW3JbEEdnYOlckO6Y/B14WCQ5QsRbo5uW6hLeVrZuScaoJPQQwJWMppbMIaNp0OCuL6ZCe+mWAUk2PDAJHq1kqKZ23NTRImjdiv0+Q2HeFAEcAlnuNbHs/gQKYzAX2MCc5u7q7NQm8MKVuj3ZriUXJaBWeBGqrdjowKK8iwDU5tHkCK72mSAdOWUWX2h1BEDx8jkcDxZWEVOFzB0yuJz8LOFfmLgHIDRe4Osm7z93KRz43V9R60uLrrW3iI/SzwO1FXaHRlCtNmpLidSpFH1NUoF5PNuf6HL3XCZuXO96hiuG8lgvjtG/Ebre9UgnesFlaVhvCbuk+iWRQTh2AoeYJZ72UJFdO3TEquRWz4f3RHQzgtNEgOU6bs7tmSJA1iX7l9/gbV3gneBT4rQoD1nKNcvS0rHEum6xJzjyDxTyg8stVnedgDJhgpDQ4jNUxnr4R3soYNOyHwulRb3VM3Ns+di3te1B77t9UoEP/Jcuw/1sR2z2UHum9sMaz2UTK6pq7gcWjQ8BnR4VLkKIdWkugC7GyyTz3wElvZE4iFZAD4T5gJaHurjvzA9/YFcQ3aDIx7ZF0QclqAs="
  # Encrypted WHITESOURCE_TOKEN for updating Whitesource licensing information
  - secure: "Jft9IV9gern2M28DDTZ9sHBZS0nwWZ5GGYMM6dRQm2IRq8/wbpZuow9YHh0+8ZDSdp72g6SZlq7/B49ZepL979T+M/i9S4ialI9foCqd6ZHwgl/vPiSUS3wH8G2JoGCujk+iuCU2UxFL0Wc4hwqP+G6ZIB7XTyIfu4h/2WQWrTIFIWSHt4ZV7Yymegz3mO7HdUErRNUTcxCKYpLRJat0JMlBuSQjvMKAtUnjzd+nnrZ33T4DO0OOu/U26Sn7ofeDWjycGyXAo5/OR0TW98K3fK1jLsdaembwmjAhx9MQpOeHODQTEwjzR72PIWWqMxNapFWxpgPbIDFM1WaLEWymFyOgysiqc6OFDt8h0wPFgceapSP0dcBpeCvG8OmPP2S2W/5vpDV00HykHqzBje4XjEDT1hdrZVF63VItB8zJJKEO/CbizeDMfwJKWN1synIAIZKmtschhFEILbr0CBC9oOpU13c3oWb7wKmdHG2iRTfPxyzQb2J7BpW/7XS5P42Yte6dQWQtECZidwdRWUOTuT8qZAGJ4VFqvys1bxQnWM+NMwxPPX+q9JhXRngliDJleVtlENWd2UVXUBIogy4ousbf68Ll4L6delKb9xmItFn3ydnhuBzJaWOe7vpfJhN2L2uyoZXCmuFl4K5mzWAMO78AeHIUup/zY7YwDEjiD+I="

script: lein do git-info-edn, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      jdk: oraclejdk8
  # Update Whitesource
  - provider: script
    skip_cleanup: true
    script: lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.3.1:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN -Dorg.whitesource.ignoredScopes=test,runtime,provided,system
    on:
      branch: master
      jdk: oraclejdk8
