sudo: false
language: clojure
lein: 2.8.1
jdk:
  - oraclejdk8
  - oraclejdk9

env:
 global:
  # Encrypted OC_TOKEN for deploying to OpenShift
  - secure: "Yh4z/Za0ZNDWlHymxYCe9MmMVhg5uZ0D23L8APfH24IRnqRZ7ephfq6xC6fiFsI99Bdy9vmut0tPy6MgP711KkiFr8UE5XzgIikaIt/sl38t0jBz3aGBWDfcelbfSILHQwirUM0UWHtJVdqY5Prcr0hy44VDrF5GVUZ9aXK/mPjN4BsQrwREVO2l7LX+Osx2geSokNpT1P6xb+2sFgHkxYuMBNtoR+EzxBRWowlhjaCm9o+CiQX1cpOjeDSgL/VGV0Q3wrpo2QNHte0B0C3lwqwZkHZzfT8nILXPbJQTwdshi5Wigt0TVP5Gpjg1umW0PMeyk63ZPj4AUj9HaczMZ5fAYELodI0G/eDLpYvVphqJlmupikOVhaclvVp2XZxiUvskexi0gCAkxK5Xt1o99drVNmlz+KjYeKI5y5ZUnoiUjpXtXDAr2m56es6OgI8n50xkNAMbXVy1vgdTCXXuJP5ibH8aImeGEr32jlbpQk/0LB75VPG74RtKfHc83ZqryyyAee5KuM5sZZdi53GIet/CluMiywsT/JQbNGHbtuWVGDsVs9sm2mYiViVpCsDThKRQwa5ihz7sdxpqSvoHsaYQ4lgJiQK3UHQWlcYsrU7p4NAqJ5SdegD25+bpCdDzY0aBuNvtARIeCRbiK6IkvFsbK4RpNjX9DmsXxmFlYIg="
  # Encrypted WHITESOURCE_TOKEN for updating Whitesource licensing information
  - secure: "Jft9IV9gern2M28DDTZ9sHBZS0nwWZ5GGYMM6dRQm2IRq8/wbpZuow9YHh0+8ZDSdp72g6SZlq7/B49ZepL979T+M/i9S4ialI9foCqd6ZHwgl/vPiSUS3wH8G2JoGCujk+iuCU2UxFL0Wc4hwqP+G6ZIB7XTyIfu4h/2WQWrTIFIWSHt4ZV7Yymegz3mO7HdUErRNUTcxCKYpLRJat0JMlBuSQjvMKAtUnjzd+nnrZ33T4DO0OOu/U26Sn7ofeDWjycGyXAo5/OR0TW98K3fK1jLsdaembwmjAhx9MQpOeHODQTEwjzR72PIWWqMxNapFWxpgPbIDFM1WaLEWymFyOgysiqc6OFDt8h0wPFgceapSP0dcBpeCvG8OmPP2S2W/5vpDV00HykHqzBje4XjEDT1hdrZVF63VItB8zJJKEO/CbizeDMfwJKWN1synIAIZKmtschhFEILbr0CBC9oOpU13c3oWb7wKmdHG2iRTfPxyzQb2J7BpW/7XS5P42Yte6dQWQtECZidwdRWUOTuT8qZAGJ4VFqvys1bxQnWM+NMwxPPX+q9JhXRngliDJleVtlENWd2UVXUBIogy4ousbf68Ll4L6delKb9xmItFn3ydnhuBzJaWOe7vpfJhN2L2uyoZXCmuFl4K5mzWAMO78AeHIUup/zY7YwDEjiD+I="

script: lein do git-info-edn, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"
      jdk: oraclejdk8
  # Update Whitesource
  - provider: script
    skip_cleanup: true
    script: lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.3.1:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN -Dorg.whitesource.ignoredScopes=test,runtime,provided,system
    on:
      branch: master
      jdk: oraclejdk8
