sudo: false
language: clojure
lein: 2.8.1
jdk:
  - oraclejdk8
  - oraclejdk9

env:
 global:
  # Encrypted OC_TOKEN for deploying to OpenShift
  - secure: "Pz83x384ugoEWBg7pkYoCVLJEgp+K7KiezWjBZH491dkjiUeypGgawvOZeOu9UPSH7QkiDXyDDm1EeJTDx+NQNM1sLQQLiTN5HuHI+aHBMPVDeME9rLZbcCi9Qz6z2/5PC7JnVFte1hRFoyp5+GPqgMKtuKIaKRNuJM1blfFa81S+YWZZtEOvTfEBq6N5xFsRYBLiD9O0ASjmWDlRxG2UdO0NnDZfhcsqsSdORAGUMSsnt6oekSz+G24VsakCgETFBU/ffuD5XvOL6Cs1GY1lt9ElWqyOHvm9jNkseb8BRd3cJC5mbv2XWMreXBCi5jWEy7h+vZ+rucFQLWIgTPTfsvrM7OoJXW3Zay2yTnHmZnB2Y9VcWrdvIEERDLT0Z/eKM+eKlnbD3kGjoAHqvdyZCOfM56Uoz3hgRwYy31K4Ma7bGPTuCXI48Fq3UGDr3hZOLYTM0F3siB2A42CfSRTqJNtHdYFXQg7BBpANJ27HBwaLipz5OLg95+O4dTfp3vfwUB5dWEeHBpJW61K0QhmSDkIQhPAmeHOb2R0JcTA52NylQfSI/iSKMstZqWVcOvsjZO78JgiXEOfCeatoQoETVj6XydzMnj0dR0XYoTdhuDs4cAWxS8Ti3jTpKEo30R62tdLnKuEGSHL+r/Pn2QEGtD/q6IEWiRus90kNtKFQ0Y="
  # Encrypted WHITESOURCE_TOKEN for updating Whitesource licensing information
  - secure: "Jft9IV9gern2M28DDTZ9sHBZS0nwWZ5GGYMM6dRQm2IRq8/wbpZuow9YHh0+8ZDSdp72g6SZlq7/B49ZepL979T+M/i9S4ialI9foCqd6ZHwgl/vPiSUS3wH8G2JoGCujk+iuCU2UxFL0Wc4hwqP+G6ZIB7XTyIfu4h/2WQWrTIFIWSHt4ZV7Yymegz3mO7HdUErRNUTcxCKYpLRJat0JMlBuSQjvMKAtUnjzd+nnrZ33T4DO0OOu/U26Sn7ofeDWjycGyXAo5/OR0TW98K3fK1jLsdaembwmjAhx9MQpOeHODQTEwjzR72PIWWqMxNapFWxpgPbIDFM1WaLEWymFyOgysiqc6OFDt8h0wPFgceapSP0dcBpeCvG8OmPP2S2W/5vpDV00HykHqzBje4XjEDT1hdrZVF63VItB8zJJKEO/CbizeDMfwJKWN1synIAIZKmtschhFEILbr0CBC9oOpU13c3oWb7wKmdHG2iRTfPxyzQb2J7BpW/7XS5P42Yte6dQWQtECZidwdRWUOTuT8qZAGJ4VFqvys1bxQnWM+NMwxPPX+q9JhXRngliDJleVtlENWd2UVXUBIogy4ousbf68Ll4L6delKb9xmItFn3ydnhuBzJaWOe7vpfJhN2L2uyoZXCmuFl4K5mzWAMO78AeHIUup/zY7YwDEjiD+I="

script: lein do git-info-edn, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"
      jdk: oraclejdk8
  # Update Whitesource
  - provider: script
    skip_cleanup: true
    script: lein pom && mvn org.whitesource:whitesource\-maven\-plugin:3.3.1:update -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN -Dorg.whitesource.ignoredScopes=test,runtime,provided,system
    on:
      branch: master
      jdk: oraclejdk8
