language: clojure
lein: 2.8.1
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10   # TravisCI deprecated their Oracle JDK 10 image, annoyingly...
  - openjdk11   # Don't fall for Oracle's trick: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

env:
 global:
  # Encrypted OC_TOKEN for deploying to OpenShift Online
  - secure: "dh8/L8K9WuWMD+ZPKyuj90gR9V1XMTQyd1I7V3D9LFC42cEfHmnpJxjHvda0CbPUxWB+yhcjQnLfIWwe6bOjrGgz30inXLBe42Xr9loJJCaapQos8rw+o+UODJXy0QgvCkk+Q9ADi5igvOVFZHiqqOTCrZ4iHuzIzYSqLQ8LZlN36a5SgDJtI8SF4m4W2z54PowtcmLGQLUlrQmKSo35aacq5IiT0bYkgUzn20iLdgXohy+h4JOHE68qyegbXlxIrETTXMx7cGttVzRriL1A8cDqqjsy72DeArxMBDqamOfWH0y+qt/c36Bf/H0Ghru+1K1MTuUCeg2909jNz4K14lFV0cHQIR3BbbfuY57+oSptwvy0oLtzhCJ5u5MD/EUhWdd/hzM+DoN1tfvip/VfiiqYhFkO41jOsor9nWH60J3t9rqfsvtAVm48MIJBVMZJPQqris04mhr3wO7HHG+lokMny8f8WlsxVMLH0DQdTPRknv7/Z0RzamWF1douV+/VWPoKge/N/yQNMIfYQBKxtjSKamIG/FMk/tsNrRz+TbAJq4ogjYk1DnkxuSpTv5gEJmscsaUjhMLMgsaDDxop9cvbOHO2AUiy2AmnvCEFGNDmXb6XBjf03avFaL238FMjJAsAYsQeGwzOAeGnecpt1Jz7UmqIazUViojjXJBSJLM="

  # Encrypted WHITESOURCE_TOKEN for updating Whitesource licensing information
  - secure: "Jft9IV9gern2M28DDTZ9sHBZS0nwWZ5GGYMM6dRQm2IRq8/wbpZuow9YHh0+8ZDSdp72g6SZlq7/B49ZepL979T+M/i9S4ialI9foCqd6ZHwgl/vPiSUS3wH8G2JoGCujk+iuCU2UxFL0Wc4hwqP+G6ZIB7XTyIfu4h/2WQWrTIFIWSHt4ZV7Yymegz3mO7HdUErRNUTcxCKYpLRJat0JMlBuSQjvMKAtUnjzd+nnrZ33T4DO0OOu/U26Sn7ofeDWjycGyXAo5/OR0TW98K3fK1jLsdaembwmjAhx9MQpOeHODQTEwjzR72PIWWqMxNapFWxpgPbIDFM1WaLEWymFyOgysiqc6OFDt8h0wPFgceapSP0dcBpeCvG8OmPP2S2W/5vpDV00HykHqzBje4XjEDT1hdrZVF63VItB8zJJKEO/CbizeDMfwJKWN1synIAIZKmtschhFEILbr0CBC9oOpU13c3oWb7wKmdHG2iRTfPxyzQb2J7BpW/7XS5P42Yte6dQWQtECZidwdRWUOTuT8qZAGJ4VFqvys1bxQnWM+NMwxPPX+q9JhXRngliDJleVtlENWd2UVXUBIogy4ousbf68Ll4L6delKb9xmItFn3ydnhuBzJaWOe7vpfJhN2L2uyoZXCmuFl4K5mzWAMO78AeHIUup/zY7YwDEjiD+I="

# Workaround for TravisCI's garbage openjdk10 base image
before_install:
  - if [[ $JAVA_HOME == *openjdk10* ]]; then rm "${JAVA_HOME}/lib/security/cacerts"; ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi

script: lein do git-info-edn, version, check

deploy:
  # Deploy binaries to OpenShift
  - provider: script
    skip_cleanup: true
    script: lein do git-info-edn, uberjar && mkdir -p target/oc && cp target/*-standalone.jar target/oc/ && ./deploy-to-openshift.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"
      jdk: openjdk11
  # Update Whitesource
  - provider: script
    skip_cleanup: true
    script: >
      lein pom &&
      mvn org.whitesource:whitesource\-maven\-plugin:18.6.2:update
      -Dorg.whitesource.orgToken=$WHITESOURCE_TOKEN
      -Dorg.whitesource.ignoredScopes=test,runtime,provided,system
      -Dorg.whitesource.failOnError=true
      -Dorg.whitesource.checkPolicies=true
      -Dorg.whitesource.forceCheckAllDependencies=true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"
      jdk: openjdk11
